# Generated by Django 3.2.3 on 2021-06-04 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NCO', '0002_newsfavourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='public',
            name='image',
        ),
    ]
